# Memoria disponible para Gradle
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

# Propiedades de Fabric
# Revisa/actualiza estos valores en https://fabricmc.net/develop si cambias de versión de Minecraft
minecraft_version=26.1.2
loader_version=0.19.3
loom_version=1.17-SNAPSHOT

# Propiedades del mod
mod_version=1.0.0
maven_group=com.tuusuario
archives_base_name=altscan

# Dependencias
fabric_api_version=0.155.2+26.1.2
