name: Build AltScan

on:
  push:
    branches: [ main ]
  workflow_dispatch: {}   # te permite lanzarlo a mano desde la pestaña Actions

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Descargar el código
        uses: actions/checkout@v4

      - name: Instalar JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'   # súbelo a 25 si tu Minecraft 26.x lo pide

      - name: Dar permisos a gradlew
        run: chmod +x ./gradlew

      - name: Compilar
        run: ./gradlew build

      - name: Subir el .jar como artifact descargable
        uses: actions/upload-artifact@v4
        with:
          name: altscan-jar
          path: build/libs/*.jar
